parameters:
  - name: /dev/openai/api-key
    value: AQICAHjv85ktIDQpafFcEZUifPBsVxaPDCfcLqbzkAoslrjJPwF9L1JaiJaju5e+7sdAME6JAAAAmjCBlwYJKoZIhvcNAQcGoIGJMIGGAgEAMIGABgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDL1Rd4MF+tSoPoBvgQIBEIBTFxOiSM/O+Sy5dP0kUi1RUd4LjrGDZvuH3bdaSD+QMCDpxNZJ1awFT3yhr+w8bKn9/1jJTqK/OUAWwdIDfDdUnMmLGwSYL/wiOtqmt3WGqUrhfjA=
secrets: []
