<%if (codeCoverage) { -%>
[tool.coverage.run]
branch = true
source = [ "<%= moduleName %>" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

<% } -%>
<%if (unitTestRunner === 'pytest' && pythonAddopts) { -%>
[tool.pytest.ini_options]
addopts = "<%- pythonAddopts %>"

<% } -%>
[tool.poetry]
name = "<%= packageName %>"
version = "1.0.0"
description = "<%= description %>"
authors = [ ]
license = 'Proprietary'
readme = 'README.md'

  [[tool.poetry.packages]]
  include = "<%= moduleName %>"

  [tool.poetry.dependencies]
  python = "<%- pyprojectPythonDependency %>"
  langchain-community = "^0.2.1"
  langchain-core = "^0.2.1"
  langchain = "^0.2.1"
  langchain-openai = "^0.1.7"
  cachetools = "^5.3.3"
  python-json-logger = "^2.0.7"
  bs4 = "^0.0.2"
  lxml = "^5.2.2"
  faiss-cpu = "1.7.4"
  vm-x-ai-extraction = "^0.1.1"

<%if (((individualPackage && !devDependenciesProject) && linter === 'flake8') || ((individualPackage && !devDependenciesProject) && unitTestRunner === 'pytest')) { -%>
  [tool.poetry.group.dev.dependencies]
  autopep8 = "2.0.2"
<%if (individualPackage && !devDependenciesProject && linter === 'flake8') { -%>
  flake8 = "6.0.0"
<% } -%>
<%if (individualPackage && !devDependenciesProject && linter === 'ruff') { -%>
  ruff = "0.1.5"
<% } -%>
<%if (individualPackage && !devDependenciesProject && unitTestRunner === 'pytest') { -%>
  pytest = "7.3.1"
  pytest-sugar = "0.9.7"
<% } -%>
<%if (individualPackage && !devDependenciesProject && unitTestRunner === 'pytest' && codeCoverage) { -%>
  pytest-cov = "4.1.0"
<% } -%>
<%if (individualPackage && !devDependenciesProject && unitTestRunner === 'pytest' && codeCoverage && codeCoverageHtmlReport) { -%>
  pytest-html = "3.2.0"
<% } -%>

<% } -%>
<%if (devDependenciesProject !== '') { -%>
  [tool.poetry.group.dev.dependencies.<%- devDependenciesProjectPkgName %>]
  path = "<%- devDependenciesProjectPath %>"
  develop = true

<% } -%>
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
<%if (individualPackage && !devDependenciesProject && linter === 'ruff') { -%>

[tool.ruff]
exclude = [
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "dist",
]

line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
ignore = []

fixable = ["ALL"]
unfixable = []
<% } -%>
